generator:
  in_channels: 1
  features: [64, 128, 256, 512, 512, 1024]
  kernel_size: 4
  stride: 2
  padding: 1
  noise_dim: 0

discriminator:
  features: [2, 64, 128, 256, 512, 1]
  kernel_size: [4, 4, 4, 4, 4]
  padding: [1, 1, 1, 1, 1]
  stride: [2, 2, 2, 1, 1]


